"use strict";
const Core=window.parent.ProjectControlsCore;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const omniUrl=document.getElementById("omniUrl"),omniKey=document.getElementById("omniKey"),omniDiag=document.getElementById("omniDiag");
const ollamaUrl=document.getElementById("ollamaUrl"),ollamaModel=document.getElementById("ollamaModel"),ollamaDiag=document.getElementById("ollamaDiag"),health=document.getElementById("health");
function load(){const o=Core.ai.config(),l=Core.ai.ollamaConfig();omniUrl.value=o.baseUrl;omniKey.value=o.endpointKey||"";ollamaUrl.value=l.baseUrl}
document.getElementById("saveOmni").onclick=()=>{Core.ai.configure({baseUrl:omniUrl.value.trim(),endpointKey:omniKey.value});omniDiag.innerHTML='<span class="ok">✓ OmniRoute settings saved.</span>'};
document.getElementById("testOmni").onclick=async e=>{const b=e.currentTarget;b.disabled=true;omniDiag.textContent="Testing OmniRoute…";try{Core.ai.configure({baseUrl:omniUrl.value.trim(),endpointKey:omniKey.value});const r=await Core.ai.testConnection();omniDiag.innerHTML=`<span class="ok">✓ Connected. ${r.modelCount} route(s); tested ${esc(r.testedModel)}.</span>`;health.textContent="OmniRoute ready"}catch(err){omniDiag.innerHTML=`<span class="bad">✕ ${esc(err?.message||err)}</span>`;health.textContent="OmniRoute issue"}finally{b.disabled=false}};
document.getElementById("detectOllama").onclick=async e=>{const b=e.currentTarget;b.disabled=true;ollamaDiag.textContent="Detecting models…";try{Core.ai.configureOllama({baseUrl:ollamaUrl.value.trim()});const m=await Core.ai.listOllamaModels();ollamaModel.innerHTML=m.length?m.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}${x.parameterSize?` · ${esc(x.parameterSize)}`:""}</option>`).join(""):'<option value="">No models installed</option>';const saved=Core.ai.ollamaConfig().model;if([...ollamaModel.options].some(x=>x.value===saved))ollamaModel.value=saved;ollamaDiag.innerHTML=m.length?`<span class="ok">✓ ${m.length} model(s) detected.</span>`:'<span class="warn">Ollama is reachable but has no installed models.</span>'}catch(err){ollamaDiag.innerHTML=`<span class="bad">✕ ${esc(err?.message||err)}</span>`}finally{b.disabled=false}};
document.getElementById("testOllama").onclick=async e=>{const b=e.currentTarget;b.disabled=true;ollamaDiag.textContent="Testing Ollama…";try{const r=await Core.ai.testOllamaConnection({baseUrl:ollamaUrl.value.trim(),model:ollamaModel.value});if(!r.ok){ollamaDiag.innerHTML=`<span class="warn">${esc(r.message)}</span>`;return}Core.ai.configureOllama({baseUrl:ollamaUrl.value.trim(),model:r.selectedModel});ollamaDiag.innerHTML=`<span class="ok">✓ Connected to ${esc(r.selectedModel)}. Test response: ${esc(r.content)}</span>`;health.textContent=`Ollama ready · ${r.selectedModel}`}catch(err){ollamaDiag.innerHTML=`<span class="bad">✕ ${esc(err?.message||err)}</span>`;health.textContent="Ollama issue"}finally{b.disabled=false}};
load();